"use client";
import React, { useState, useRef, useEffect, Suspense } from 'react';
import { useNavigate } from 'react-router-dom';
import { ShortenedLink } from '../types';
import { useLocalStorage } from '../hooks/useLocalStorage';
import { Card, Button, Input } from '../components/UI';
// Fix: Use ES module import for QRCodeSVG instead of require.
import { QRCodeCanvas, QRCodeSVG } from 'qrcode.react';
import { motion, AnimatePresence } from 'framer-motion';
import toast, { Toaster } from 'react-hot-toast';
import { Link as LinkIcon, ClipboardCopy, Download, Share2, Twitter, Facebook, Linkedin, Code, Settings, ChevronDown, RefreshCw } from 'lucide-react';
import { CyberpunkBox, AnimatedSpaceship } from '../components/Cyberpunk';
import AdSlot from '../components/AdSlot';
import AdConsent from '../components/AdConsent';
import AdsterraBanner from '../components/AdsterraBanner';
// Fix: Add a side-effect import for '@react-three/fiber'. This enables its
// JSX type augmentations, making Three.js elements like <mesh> and <pointLight>
// available in JSX and resolving all related TypeScript errors in this file.
import '@react-three/fiber';

const WhatsAppIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor" {...props}>
        <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.894 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.886-.001 2.267.651 4.383 1.905 6.344l-1.196 4.359 4.559-1.187zM8.341 7.218c-.375-.164-.848-.158-1.291.096-.442.253-.729.569-.871.849-.142.28-.214.61-.173.945.041.335.214.643.465.918.251.275.586.583.992.949.406.366.848.775 1.328 1.229.833.731 1.523 1.24 2.228 1.583.704.344 1.358.471 1.923.428.566-.043 1.063-.24 1.408-.569.345-.329.516-.769.516-1.242 0-.472-.172-.882-.516-1.221-.345-.338-.82-.519-1.348-.519h-.12c-.221 0-.438.03-.647.09-.209.06-.403.119-.581.119-.179 0-.375-.059-.553-.178-.178-.119-.383-.265-.61-.438-.459-.353-.847-.799-1.162-1.221-.314-.423-.471-.899-.471-1.378 0-.119.014-.248.043-.387.028-.139.085-.258.171-.357.086-.1.199-.143.34-.143.099 0 .199.014.285.043.086.028.188.071.303.128.115.057.217.086.303.086.131 0 .277-.02.438-.061.162-.041.324-.099.465-.178.142-.078.259-.164.35-.258.09-.095.143-.209.157-.341a.846.846 0 00-.043-.516c-.071-.24-.2-.464-.383-.671z"/>
    </svg>
);

const InstagramIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
        <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
        <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
        <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
    </svg>
);


const SocialShareButtons: React.FC<{ url: string }> = ({ url }) => {
    const encodedUrl = encodeURIComponent(url);
    const text = encodeURIComponent("Check out this link generated by Qbit!");

    const handleInstagramClick = (e: React.MouseEvent<HTMLAnchorElement, MouseEvent>) => {
        e.preventDefault();
        navigator.clipboard.writeText(url);
        toast.success('Link copied! Ready to share on Instagram.', {
            style: { background: '#1a1a1a', color: '#ff8c00', border: '1px solid #ff8c00' },
            iconTheme: { primary: '#ff8c00', secondary: '#1a1a1a' },
        });
    };

    const platforms = [
        { name: 'WhatsApp', icon: <WhatsAppIcon />, url: `https://api.whatsapp.com/send?text=${text}%20${encodedUrl}` },
        { name: 'Twitter', icon: <Twitter size={20} />, url: `https://twitter.com/intent/tweet?url=${encodedUrl}&text=${text}` },
        { name: 'Facebook', icon: <Facebook size={20} />, url: `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}` },
        { name: 'LinkedIn', icon: <Linkedin size={20} />, url: `https://www.linkedin.com/shareArticle?mini=true&url=${encodedUrl}` },
        { name: 'Instagram', icon: <InstagramIcon />, url: '#', onClick: handleInstagramClick }
    ];

    return (
        <div className="flex items-center gap-2">
            {platforms.map(p => (
                <a
                  key={p.name}
                  href={p.url}
                  onClick={p.onClick}
                  target={p.onClick ? '_self' : '_blank'}
                  rel="noopener noreferrer"
                  className="p-2 bg-white/5 hover:bg-white/10 rounded-full transition-colors text-gray-300"
                  title={`Share on ${p.name}`}
                  aria-label={`Share on ${p.name}`}
                >
                    {p.icon}
                </a>
            ))}
        </div>
    );
}

const ResultCard: React.FC<{ link: ShortenedLink }> = ({ link }) => {
    const qrRef = useRef<HTMLDivElement>(null);

    const copyToClipboard = (text: string) => {
        navigator.clipboard.writeText(text);
        toast.success('Copied to clipboard!', {
            style: { background: '#1a1a1a', color: '#ff8c00', border: '1px solid #ff8c00' },
            iconTheme: { primary: '#ff8c00', secondary: '#1a1a1a' },
        });
    };

    const downloadQRCode = (format: 'png' | 'jpeg' | 'svg') => {
        if (!qrRef.current) return;
        const canvas = qrRef.current.querySelector('canvas');
        
        if (format === 'svg') {
            const svgEl = qrRef.current.querySelector('svg');
            if (svgEl) {
                const svgData = new XMLSerializer().serializeToString(svgEl);
                const blob = new Blob([svgData], { type: "image/svg+xml;charset=utf-8" });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `qbit-qr-${link.id}.svg`;
                a.click();
                URL.revokeObjectURL(url);
            }
            return;
        }

        if (canvas) {
            const url = canvas.toDataURL(`image/${format}`);
            const a = document.createElement('a');
            a.href = url;
            a.download = `qbit-qr-${link.id}.${format}`;
            a.click();
        }
    };
    
    return (
        <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -50 }}
            transition={{ type: 'spring' }}
            className="w-full"
        >
            <Card className="p-4 md:p-6">
                <div className="flex flex-col md:flex-row gap-6">
                    <div className="flex-grow">
                        <p className="text-sm text-gray-400 mb-2 truncate" title={link.longUrl}>Original: {link.longUrl}</p>
                        <div className="flex items-center gap-2 bg-black/50 p-3 theme-border">
                            <a href={link.longUrl} target="_blank" rel="noopener noreferrer" className="text-orange-300 flex-grow break-all hover:text-orange-100" title={`Redirects to: ${link.longUrl}`}>{link.shortUrl.replace('https://qbit.link', 'Qbit')}</a>
                            <button onClick={() => copyToClipboard(link.shortUrl)} className="p-2 hover:bg-white/10 rounded-full transition-colors text-gray-300" aria-label="Copy short link">
                                <ClipboardCopy size={18} />
                            </button>
                        </div>
                        <div className="mt-4 flex items-center gap-4">
                            <Share2 className="text-yellow-400"/>
                            <SocialShareButtons url={link.shortUrl} />
                        </div>
                    </div>
                    <div className="flex-shrink-0 text-center">
                        <div ref={qrRef} className="bg-white p-2 inline-block">
                             <QRCodeSVG value={link.longUrl} size={128} includeMargin={false} />
                             <div className="hidden"><QRCodeCanvas value={link.longUrl} size={512} includeMargin={true} /></div>
                        </div>
                        <div className="mt-2 flex justify-center gap-2">
                           <Button onClick={() => downloadQRCode('png')} variant="secondary" className="!px-3 !py-1 !text-xs" aria-label="Download QR code as PNG"><Download size={12} className="inline mr-1"/>PNG</Button>
                           <Button onClick={() => downloadQRCode('jpeg')} variant="secondary" className="!px-3 !py-1 !text-xs" aria-label="Download QR code as JPEG"><Download size={12} className="inline mr-1"/>JPG</Button>
                           <Button onClick={() => downloadQRCode('svg')} variant="secondary" className="!px-3 !py-1 !text-xs" aria-label="Download QR code as SVG"><Download size={12} className="inline mr-1"/>SVG</Button>
                        </div>
                    </div>
                </div>
                 <p className="text-xs text-yellow-500/70 mt-4 text-center">
                    ⚠️ Do not use shortened links for phishing, scams, or harmful activity.
                </p>
            </Card>
        </motion.div>
    );
};

const MobileAd: React.FC = () => {
    // Note: Replace '1234567890' with your actual AdSense ad slot ID for mobile.
    return <AdSlot id="ad-bottom" adClient="ca-pub-3803108248367773" adSlot="1234567890" style={{ position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 9999, textAlign: 'center' }} />;
};


const HomePage: React.FC = () => {
    const [longUrl, setLongUrl] = useState('');
    const [customAlias, setCustomAlias] = useState('');
    const [showAdvanced, setShowAdvanced] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [result, setResult] = useState<ShortenedLink | null>(null);
    const [links, setLinks] = useLocalStorage<ShortenedLink[]>('qbit-links', []);
    const navigate = useNavigate();
    const [adConsentGiven, setAdConsentGiven] = useState(true);
    const [isMobile, setIsMobile] = useState(false);


    useEffect(() => {
        // Check consent status on mount
        setAdConsentGiven(localStorage.getItem('qbit_ad_consent') === 'true');

        // Check mobile status
        const checkSize = () => {
            setIsMobile(typeof window !== 'undefined' && window.innerWidth < 900);
        };
        checkSize();
        window.addEventListener('resize', checkSize);
        return () => window.removeEventListener('resize', checkSize);
    }, []);

    useEffect(() => {
        // Manage body padding based on component visibility to prevent footer overlap
        let padding = 0;
        if (!adConsentGiven) {
            padding = 70; // Height for AdConsent banner
        } else if (isMobile) {
            padding = 50; // Height for MobileAd banner
        }
        document.body.style.paddingBottom = `${padding}px`;

        // Cleanup function to reset padding when navigating away from the home page
        return () => {
            document.body.style.paddingBottom = '0';
        };
    }, [adConsentGiven, isMobile]);

    const handleConsentDismiss = () => {
        localStorage.setItem('qbit_ad_consent', 'true');
        setAdConsentGiven(true);
    };

    const MOCK_COUNTRIES = ['USA', 'Germany', 'Japan', 'Brazil', 'India', 'UK'];

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (!longUrl) {
            toast.error('Please enter a URL to shorten.', {
                 style: { background: '#1a1a1a', color: '#ff8c00', border: '1px solid #ff8c00' },
                 iconTheme: { primary: '#ff8c00', secondary: '#1a1a1a' },
            });
            return;
        }

        if (customAlias && links.some(l => l.customAlias === customAlias)) {
            toast.error('This custom alias is already taken.', {
                 style: { background: '#1a1a1a', color: '#ff8c00', border: '1px solid #ff8c00' },
                 iconTheme: { primary: '#ff8c00', secondary: '#1a1a1a' },
            });
            return;
        }

        setIsLoading(true);

        setTimeout(() => {
            const id = Math.random().toString(36).substring(2, 8);
            const newLink: ShortenedLink = {
                id,
                longUrl,
                shortUrl: `https://qbit.link/${customAlias || id}`,
                customAlias: customAlias || undefined,
                qrCodeUrl: `https://qbit.link/qr/${id}`,
                createdAt: new Date().toISOString(),
                clicks: Math.floor(Math.random() * 1000),
                geoData: MOCK_COUNTRIES.sort(() => 0.5 - Math.random()).slice(0, 4).map(country => ({
                    country,
                    clicks: Math.floor(Math.random() * 200) + 10,
                })).sort((a, b) => b.clicks - a.clicks)
            };

            setResult(newLink);
            setLinks(prevLinks => [...prevLinks, newLink]);
            setIsLoading(false);
        }, 1500);
    };

    const handleShortenAnother = () => {
        setResult(null);
        setLongUrl('');
        setCustomAlias('');
        setShowAdvanced(false);
    };

    return (
        <>
        <CyberpunkBox />
        <div className="fixed bottom-32 left-16 z-[1] opacity-40 pointer-events-none">
            <AnimatedSpaceship />
        </div>
        <div className="relative z-10 flex flex-col items-center justify-center min-h-[calc(100vh-12rem)] px-4 text-center">
            <Toaster position="bottom-center" />
             <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="flex flex-col items-center justify-center w-full"
            >
                <h1 className="text-5xl md:text-7xl font-orbitron font-bold text-orange-400 theme-glow-primary">
                    Qbit Shortener
                </h1>
            </motion.div>
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5, delay: 0.2 }}>
                <p className="mt-2 max-w-2xl text-lg text-gray-300">
                    A link shortening service from the future. Fast, reliable, and supercharged with instant QR code generation.
                </p>
            </motion.div>

            <div className="w-full max-w-2xl mt-6">
                <AnimatePresence mode="wait">
                    {!result ? (
                        <motion.div
                            key="form-wrapper"
                            className="w-full"
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -20 }}
                            transition={{ duration: 0.3 }}
                        >
                            <form
                                onSubmit={handleSubmit}
                                className="w-full"
                            >
                                <div className="relative w-full">
                                    <div className="relative z-10 bg-black/40 backdrop-blur-md p-4 shadow-lg shadow-orange-500/20 flex flex-col gap-4 theme-border">
                                        <div className="flex flex-col gap-4">
                                            <Input
                                                icon={<LinkIcon size={18} />}
                                                type="url"
                                                placeholder="Enter a long URL to shorten..."
                                                value={longUrl}
                                                onChange={(e) => setLongUrl(e.target.value)}
                                                required
                                                aria-label="URL to shorten"
                                            />
                                            <div>
                                                <button type="button" onClick={() => setShowAdvanced(!showAdvanced)} className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors">
                                                    <Settings size={14} />
                                                    Advanced Options
                                                    <ChevronDown size={16} className={`transition-transform ${showAdvanced ? 'rotate-180' : ''}`} />
                                                </button>
                                                <AnimatePresence>
                                                    {showAdvanced && (
                                                        <motion.div
                                                            initial={{ height: 0, opacity: 0, marginTop: 0 }}
                                                            animate={{ height: 'auto', opacity: 1, marginTop: '0.75rem' }}
                                                            exit={{ height: 0, opacity: 0, marginTop: 0 }}
                                                            className="overflow-hidden"
                                                        >
                                                            <Input
                                                                icon={<Code size={18} />}
                                                                type="text"
                                                                placeholder="Custom alias (e.g., my-event)"
                                                                value={customAlias}
                                                                onChange={(e) => setCustomAlias(e.target.value.replace(/\s+/g, '-'))}
                                                                aria-label="Custom alias"
                                                            />
                                                        </motion.div>
                                                    )}
                                                </AnimatePresence>
                                            </div>
                                        </div>
                                        
                                        <Button type="submit" disabled={isLoading} className="w-full">
                                            {isLoading ? 'ENCODING...' : 'Shorten'}
                                        </Button>
                                    </div>
                                    <div className="ad-cluster mt-6">
                                        <AdsterraBanner id="300x250_main" />
                                    </div>
                                </div>
                            </form>
                        </motion.div>
                    ) : (
                        <motion.div
                            key="result"
                            className="w-full flex flex-col items-center"
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -20 }}
                            transition={{ duration: 0.3 }}
                        >
                            <ResultCard link={result} />
                            <div className="flex items-center gap-4 mt-4">
                                <Button
                                    onClick={handleShortenAnother}
                                    className="flex items-center gap-2"
                                    variant="secondary"
                                >
                                    <RefreshCw size={14} />
                                    Shorten Another URL
                                </Button>
                                <Button
                                    onClick={() => navigate('/dashboard')}
                                    className="flex items-center gap-2"
                                >
                                    View Dashboard
                                </Button>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
        {isMobile && <MobileAd />}
        {!adConsentGiven && <AdConsent onDismiss={handleConsentDismiss} />}
        </>
    );
};

export default HomePage;