import React, { useState, useRef, useEffect, Suspense } from 'react';
import { useNavigate } from 'react-router-dom';
import { ShortenedLink } from '../types';
import { useLocalStorage } from '../hooks/useLocalStorage';
import { Card, Button, Input } from '../components/UI';
// Fix: Use ES module import for QRCodeSVG instead of require.
import { QRCodeCanvas, QRCodeSVG } from 'qrcode.react';
import { motion, AnimatePresence } from 'framer-motion';
import toast, { Toaster } from 'react-hot-toast';
import { Link as LinkIcon, ClipboardCopy, Download, Share2, Twitter, Facebook, Linkedin, Code, Settings, ChevronDown, RefreshCw } from 'lucide-react';
import { CyberpunkBox, AnimatedSpaceship } from '../components/Cyberpunk';
import AdSlot from '../components/AdSlot';
import AdConsent from '../components/AdConsent';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import type * as THREE from 'three';

const AnimatedWireframe: React.FC = () => {
    const meshRef = useRef<THREE.Mesh>(null!);
    const { viewport } = useThree();

    // Scale the wireframe to be slightly smaller than the container width
    const scale = viewport.width / 3.5;

    useFrame((_state, delta) => {
        if (meshRef.current) {
            meshRef.current.rotation.y += delta * 0.1;
            meshRef.current.rotation.x += delta * 0.05;
        }
    });

    return (
        <mesh ref={meshRef} scale={scale}>
            <icosahedronGeometry args={[1, 1]} />
            <meshStandardMaterial
                color="#ff8c00"
                emissive="#ff8c00"
                emissiveIntensity={2.5}
                wireframe
                transparent
                opacity={0.5}
                toneMapped={false}
            />
        </mesh>
    );
};

const AnimatedFormCard: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <div className="relative">
            <div className="absolute -inset-4 z-0 opacity-70">
                <Canvas camera={{ position: [0, 0, 5], fov: 75 }}>
                    <ambientLight intensity={0.2} />
                    <pointLight position={[0, 0, 5]} color="#ff8c00" intensity={4} />
                    <Suspense fallback={null}>
                        <AnimatedWireframe />
                    </Suspense>
                </Canvas>
            </div>
            <div className="relative z-10 bg-black/20 backdrop-blur-sm border border-orange-400/30 p-4 shadow-lg shadow-orange-500/20">
                {children}
            </div>
        </div>
    );
};


const SocialShareButtons: React.FC<{ url: string }> = ({ url }) => {
    const encodedUrl = encodeURIComponent(url);
    const text = encodeURIComponent("Check out this link generated by Qbit!");

    const platforms = [
        { name: 'Twitter', icon: <Twitter size={20} />, url: `https://twitter.com/intent/tweet?url=${encodedUrl}&text=${text}` },
        { name: 'Facebook', icon: <Facebook size={20} />, url: `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}` },
        { name: 'LinkedIn', icon: <Linkedin size={20} />, url: `https://www.linkedin.com/shareArticle?mini=true&url=${encodedUrl}` }
    ];

    return (
        <div className="flex items-center gap-2">
            {platforms.map(p => (
                <a key={p.name} href={p.url} target="_blank" rel="noopener noreferrer" className="p-2 bg-white/5 hover:bg-white/10 rounded-full transition-colors text-gray-300" title={`Share on ${p.name}`} aria-label={`Share on ${p.name}`}>
                    {p.icon}
                </a>
            ))}
        </div>
    );
}

const ResultCard: React.FC<{ link: ShortenedLink }> = ({ link }) => {
    const qrRef = useRef<HTMLDivElement>(null);

    const copyToClipboard = (text: string) => {
        navigator.clipboard.writeText(text);
        toast.success('Copied to clipboard!', {
            style: { background: '#1a1a1a', color: '#ff8c00', border: '1px solid #ff8c00' },
            iconTheme: { primary: '#ff8c00', secondary: '#1a1a1a' },
        });
    };

    const downloadQRCode = (format: 'png' | 'jpeg' | 'svg') => {
        if (!qrRef.current) return;
        const canvas = qrRef.current.querySelector('canvas');
        
        if (format === 'svg') {
            const svgEl = qrRef.current.querySelector('svg');
            if (svgEl) {
                const svgData = new XMLSerializer().serializeToString(svgEl);
                const blob = new Blob([svgData], { type: "image/svg+xml;charset=utf-8" });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `qbit-qr-${link.id}.svg`;
                a.click();
                URL.revokeObjectURL(url);
            }
            return;
        }

        if (canvas) {
            const url = canvas.toDataURL(`image/${format}`);
            const a = document.createElement('a');
            a.href = url;
            a.download = `qbit-qr-${link.id}.${format}`;
            a.click();
        }
    };
    
    return (
        <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -50 }}
            transition={{ type: 'spring' }}
            className="w-full"
        >
            <Card className="p-4 md:p-6">
                <div className="flex flex-col md:flex-row gap-6">
                    <div className="flex-grow">
                        <p className="text-sm text-gray-400 mb-2 truncate" title={link.longUrl}>Original: {link.longUrl}</p>
                        <div className="flex items-center gap-2 bg-black/50 p-3 theme-border">
                            <a href={link.longUrl} target="_blank" rel="noopener noreferrer" className="text-orange-300 flex-grow break-all hover:text-orange-100" title={`Redirects to: ${link.longUrl}`}>{link.shortUrl.replace('https://qbit.link', 'Qbit')}</a>
                            <button onClick={() => copyToClipboard(link.shortUrl)} className="p-2 hover:bg-white/10 rounded-full transition-colors text-gray-300" aria-label="Copy short link">
                                <ClipboardCopy size={18} />
                            </button>
                        </div>
                        <div className="mt-4 flex items-center gap-4">
                            <Share2 className="text-yellow-400"/>
                            <SocialShareButtons url={link.shortUrl} />
                        </div>
                    </div>
                    <div className="flex-shrink-0 text-center">
                        <div ref={qrRef} className="bg-white p-2 inline-block">
                             <QRCodeSVG value={link.shortUrl} size={128} includeMargin={false} />
                             <div className="hidden"><QRCodeCanvas value={link.shortUrl} size={512} includeMargin={true} /></div>
                        </div>
                        <div className="mt-2 flex justify-center gap-2">
                           <Button onClick={() => downloadQRCode('png')} variant="secondary" className="!px-3 !py-1 !text-xs" aria-label="Download QR code as PNG"><Download size={12} className="inline mr-1"/>PNG</Button>
                           <Button onClick={() => downloadQRCode('jpeg')} variant="secondary" className="!px-3 !py-1 !text-xs" aria-label="Download QR code as JPEG"><Download size={12} className="inline mr-1"/>JPG</Button>
                           <Button onClick={() => downloadQRCode('svg')} variant="secondary" className="!px-3 !py-1 !text-xs" aria-label="Download QR code as SVG"><Download size={12} className="inline mr-1"/>SVG</Button>
                        </div>
                    </div>
                </div>
                 <p className="text-xs text-yellow-500/70 mt-4 text-center">
                    ⚠️ Do not use shortened links for phishing, scams, or harmful activity.
                </p>
            </Card>
        </motion.div>
    );
};

const MobileAd: React.FC = () => {
    const [isMobile, setIsMobile] = useState(false);

    useEffect(() => {
        const checkSize = () => {
            setIsMobile(typeof window !== 'undefined' && window.innerWidth < 900);
        };
        checkSize();
        window.addEventListener('resize', checkSize);
        return () => window.removeEventListener('resize', checkSize);
    }, []);

    if (!isMobile) {
        return null;
    }

    return <AdSlot id="ad-bottom" adClient="ca-pub-XXXXXXXXXXXXXXXX" adSlot="WWWWWWWWWW" style={{ position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 9999, textAlign: 'center' }} />;
};


const HomePage: React.FC = () => {
    const [longUrl, setLongUrl] = useState('');
    const [customAlias, setCustomAlias] = useState('');
    const [showAdvanced, setShowAdvanced] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [result, setResult] = useState<ShortenedLink | null>(null);
    const [links, setLinks] = useLocalStorage<ShortenedLink[]>('qbit-links', []);
    const navigate = useNavigate();

    const MOCK_COUNTRIES = ['USA', 'Germany', 'Japan', 'Brazil', 'India', 'UK'];

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (!longUrl) {
            toast.error('Please enter a URL to shorten.', {
                 style: { background: '#1a1a1a', color: '#ff8c00', border: '1px solid #ff8c00' },
                 iconTheme: { primary: '#ff8c00', secondary: '#1a1a1a' },
            });
            return;
        }

        if (customAlias && links.some(l => l.customAlias === customAlias)) {
            toast.error('This custom alias is already taken.', {
                 style: { background: '#1a1a1a', color: '#ff8c00', border: '1px solid #ff8c00' },
                 iconTheme: { primary: '#ff8c00', secondary: '#1a1a1a' },
            });
            return;
        }

        setIsLoading(true);

        setTimeout(() => {
            const id = Math.random().toString(36).substring(2, 8);
            const newLink: ShortenedLink = {
                id,
                longUrl,
                shortUrl: `https://qbit.link/${customAlias || id}`,
                customAlias: customAlias || undefined,
                qrCodeUrl: `https://qbit.link/qr/${id}`,
                createdAt: new Date().toISOString(),
                clicks: Math.floor(Math.random() * 1000),
                geoData: MOCK_COUNTRIES.sort(() => 0.5 - Math.random()).slice(0, 4).map(country => ({
                    country,
                    clicks: Math.floor(Math.random() * 200) + 10,
                })).sort((a, b) => b.clicks - a.clicks)
            };

            setResult(newLink);
            setLinks(prevLinks => [...prevLinks, newLink]);
            setIsLoading(false);
        }, 1500);
    };

    const handleShortenAnother = () => {
        setResult(null);
        setLongUrl('');
        setCustomAlias('');
        setShowAdvanced(false);
    };

    return (
        <>
        <CyberpunkBox />
        <div className="fixed bottom-32 left-16 z-0 opacity-40 pointer-events-none">
            <AnimatedSpaceship />
        </div>
        <div className="relative z-10 flex flex-col items-center justify-center min-h-[calc(100vh-12rem)] px-4 text-center">
            <Toaster position="bottom-center" />
             <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="flex flex-col items-center justify-center w-full"
            >
                <h1 className="text-5xl md:text-7xl font-orbitron font-bold text-white theme-glow-primary">
                    Qbit Shortener
                </h1>
            </motion.div>
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5, delay: 0.2 }}>
                <p className="mt-2 max-w-2xl text-lg text-gray-400">
                    A link shortening service from the future. Fast, reliable, and supercharged with instant QR code generation.
                </p>
            </motion.div>

            <div className="w-full max-w-2xl mt-6">
                <AnimatePresence mode="wait">
                    {!result ? (
                        <motion.div
                            key="form-wrapper"
                            className="w-full"
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -20 }}
                            transition={{ duration: 0.3 }}
                        >
                            <form
                                onSubmit={handleSubmit}
                                className="w-full"
                            >
                                <AnimatedFormCard>
                                    <div className="flex flex-col gap-4">
                                        <Input
                                            icon={<LinkIcon size={18} />}
                                            type="url"
                                            placeholder="Enter a long URL to shorten..."
                                            value={longUrl}
                                            onChange={(e) => setLongUrl(e.target.value)}
                                            required
                                            aria-label="URL to shorten"
                                        />

                                        <div>
                                            <button type="button" onClick={() => setShowAdvanced(!showAdvanced)} className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors">
                                                <Settings size={14} />
                                                Advanced Options
                                                <ChevronDown size={16} className={`transition-transform ${showAdvanced ? 'rotate-180' : ''}`} />
                                            </button>
                                            <AnimatePresence>
                                                {showAdvanced && (
                                                    <motion.div
                                                        initial={{ height: 0, opacity: 0, marginTop: 0 }}
                                                        animate={{ height: 'auto', opacity: 1, marginTop: '0.75rem' }}
                                                        exit={{ height: 0, opacity: 0, marginTop: 0 }}
                                                        className="overflow-hidden"
                                                    >
                                                        <Input
                                                            icon={<Code size={18} />}
                                                            type="text"
                                                            placeholder="Custom alias (e.g., my-event)"
                                                            value={customAlias}
                                                            onChange={(e) => setCustomAlias(e.target.value.replace(/\s+/g, '-'))}
                                                            aria-label="Custom alias"
                                                       />
                                                    </motion.div>
                                                )}
                                            </AnimatePresence>
                                        </div>
                                        <Button type="submit" disabled={isLoading} className="w-full">
                                            {isLoading ? 'ENCODING...' : 'Shorten'}
                                        </Button>
                                    </div>
                                </AnimatedFormCard>
                            </form>
                            <AdSlot id="ad-inline" adClient="ca-pub-XXXXXXXXXXXXXXXX" adSlot="ZZZZZZZZZZ" style={{ margin: "16px auto", maxWidth: 728, width: "100%" }} />
                        </motion.div>
                    ) : (
                        <motion.div
                            key="result"
                            className="w-full flex flex-col items-center"
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -20 }}
                            transition={{ duration: 0.3 }}
                        >
                            <ResultCard link={result} />
                            <div className="flex items-center gap-4 mt-4">
                                <Button
                                    onClick={handleShortenAnother}
                                    className="flex items-center gap-2"
                                    variant="secondary"
                                >
                                    <RefreshCw size={14} />
                                    Shorten Another URL
                                </Button>
                                <Button
                                    onClick={() => navigate('/dashboard')}
                                    className="flex items-center gap-2"
                                >
                                    View Dashboard
                                </Button>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
        <MobileAd />
        <AdConsent />
        </>
    );
};

export default HomePage;